title: Nick Moline
description: Personal website of Nicholas Moline, Senior Software Engineer at Justia
cover: /background-jellybean.jpg
logo: /monogram.png
favicon: assets/images/favicon.png
baseurl: ""
url: https://nickmoline.github.io
name: nickmoline.com
excerpt_separator: <!--more-->

defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "nickmoline"

paginate: 10
paginate_path: "/blog/page:num/"

facebook: nickmoline
twitter: NickMoline
github: nickmoline
linkedin: nickmoline


about: about
contact: contact
privacy-policy: privacy-policy

permalink: /:year/:month/:day/:title/

analytics_id: UA-1093504-1

markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-feed
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jemoji

safe: false
lsi: false
username: nickmoline
repo: nickmoline.github.io
branch: master
production_url: https://nickmoline.github.io
source_url: https://github.com/nickmoline/nickmoline.github.io

sass:
  style: compressed

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - .gitignore
  - _pending