title: Nick Moline
description: Senior Software Engineer at Justia, Tech Wizard for Harry Potter Lexicon, Theatre Sound Designer.
cover: /background-jellybean.jpg
coverp: /background-jellybean.webp
logo: /monogram.png
logop: /monogram.webp
favicon: /wp-content/uploads/sites/4/2016/10/cropped-100_1381-1-1.jpg
baseurl: ""
url: https://www.nickmoline.com
name: nickmoline.com
excerpt_separator: <!--more-->

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "nickmoline"

paginate: 10
paginate_path: "/blog/page:num/"

facebook: nickmoline
twitter: NickMoline
github: nickmoline
linkedin: nickmoline
youtube: nickmoline

about: 
contact: 
privacy-policy: /privacy-policy.html

permalink: /:year/:month/:day/:title/

analytics_id: UA-1093504-1

markdown: kramdown

kramdown:
    parse_block_html: false

plugins:
    - jekyll-paginate
    - jekyll-github-metadata
    - jekyll-feed
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jemoji
    - jekyll-last-modified-at

safe: false
lsi: false
username: nickmoline
repo: nickmoline.github.io
repository: nickmoline/nickmoline.github.io
branch: master
production_url: https://www.nickmoline.com
source_url: https://github.com/nickmoline/nickmoline.github.io

sass:
    style: compressed

exclude:
    - Rakefile
    - Gemfile
    - Gemfile.lock
    - "*.Rmd"
    - vendor
    - .travis.yml
    - .gitignore

include:
    - .well-known